============================= test session starts ==============================
rootdir: $(SOURCE_DIR), inifile: pytest.ini
collected 14 items / 4 errors

tempora/__init__.py ..........
tempora/timing.py ...

==================================== ERRORS ====================================
_______________ ERROR collecting tempora/tests/test_schedule.py ________________
tempora/tests/test_schedule.py:7: in <module>
    import freezegun
E   ImportError: No module named freezegun
_______________ ERROR collecting tempora/tests/test_schedule.py ________________
tempora/tests/test_schedule.py:7: in <module>
    import freezegun
E   ImportError: No module named freezegun
____________________ ERROR collecting tests/test_timing.py _____________________
tests/test_timing.py:5: in <module>
    from unittest import mock
E   ImportError: cannot import name mock
____________________ ERROR collecting tests/test_timing.py _____________________
tests/test_timing.py:5: in <module>
    from unittest import mock
E   ImportError: cannot import name mock
====================== 13 passed, 4 error in  x seconds ======================
