 test session starts ==============================
cachedir: .cache
rootdir: $(SOURCE_DIR), inifile: pytest.ini
collecting ... collected 27 items / 37 errors

cherrypy/lib/httputil.py::cherrypy.lib.httputil.decode_TEXT PASSED
cherrypy/lib/httputil.py::cherrypy.lib.httputil.valid_status PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn/-/pi/-/sn/pi/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn/-/pi-/sn/pi] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn/-/-/sn/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn/--/sn/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn-/pi/-/sn/pi/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn-/pi-/sn/pi] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn-/-/sn/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/sn--/sn] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/-/pi/-/pi/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/-/pi-/pi] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/-/-/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[/--/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[-/pi/-/pi/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[-/pi-/pi] PASSED
cherrypy/test/test_httputil.py::test_urljoin[-/-/] PASSED
cherrypy/test/test_httputil.py::test_urljoin[--/] PASSED
cherrypy/test/test_httputil.py::test_valid_status[None-expected_status0] PASSED
cherrypy/test/test_httputil.py::test_valid_status[200-expected_status1] PASSED
cherrypy/test/test_httputil.py::test_valid_status[500-expected_status2] PASSED
cherrypy/test/test_httputil.py::test_valid_status[HTTPStatus.NOT_FOUND-expected_status3] PASSED
cherrypy/test/test_httputil.py::test_valid_status[444 Non-existent reason-expected_status4] PASSED
cherrypy/test/test_httputil.py::test_invalid_status[hey-Illegal response status from server ('hey' is non-numeric).] PASSED
cherrypy/test/test_httputil.py::test_invalid_status[status_code1-Illegal response status from server ({'hey': 'hi'} is non-numeric).] PASSED
cherrypy/test/test_httputil.py::test_invalid_status[1-Illegal response status from server (1 is out of range).] PASSED
cherrypy/test/test_httputil.py::test_invalid_status[600-Illegal response status from server (600 is out of range).] PASSED

 generated xml file: $(SOURCE_DIR)/.test-results/pytest/results.xml 
 ERRORS ====================================
______________ ERROR collecting cherrypy/test/test_auth_basic.py _______________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
______________ ERROR collecting cherrypy/test/test_auth_digest.py ______________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
__________________ ERROR collecting cherrypy/test/test_bus.py __________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_caching.py ________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_compat.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_config.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_____________ ERROR collecting cherrypy/test/test_config_server.py _____________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_conn.py __________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_core.py __________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________ ERROR collecting cherrypy/test/test_dynamicobjectmapping.py __________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_______________ ERROR collecting cherrypy/test/test_encoding.py ________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_etags.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_http.py __________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_______________ ERROR collecting cherrypy/test/test_iterator.py ________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_json.py __________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_logging.py ________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_mime.py __________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
______________ ERROR collecting cherrypy/test/test_misc_tools.py _______________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_____________ ERROR collecting cherrypy/test/test_objectmapping.py _____________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_params.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_proxy.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_______________ ERROR collecting cherrypy/test/test_refleaks.py ________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
______________ ERROR collecting cherrypy/test/test_request_obj.py ______________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_routes.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_session.py ________________
cherrypy/test/test_session.py:10: in <module>
    from path import Path
E   ModuleNotFoundError: No module named 'path'
________________ ERROR collecting cherrypy/test/test_session.py ________________
cherrypy/test/test_session.py:10: in <module>
    from path import Path
E   ModuleNotFoundError: No module named 'path'
__________ ERROR collecting cherrypy/test/test_sessionauthenticate.py __________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_states.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_static.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_________________ ERROR collecting cherrypy/test/test_tools.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_______________ ERROR collecting cherrypy/test/test_tutorials.py _______________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
______________ ERROR collecting cherrypy/test/test_virtualhost.py ______________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_wsgi_ns.py ________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
___________ ERROR collecting cherrypy/test/test_wsgi_unix_socket.py ____________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
______________ ERROR collecting cherrypy/test/test_wsgi_vhost.py _______________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
_______________ ERROR collecting cherrypy/test/test_wsgiapps.py ________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
________________ ERROR collecting cherrypy/test/test_xmlrpc.py _________________
/usr/lib/python3.7/vendor-packages/_pytest/runner.py:150: in __init__
    self.result = func()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/main.py:315: in _memoizedcall
    res = function()
/usr/lib/python3.7/vendor-packages/_pytest/main.py:435: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
/usr/lib/python3.7/vendor-packages/_pytest/python.py:605: in collect
    return super(Module, self).collect()
/usr/lib/python3.7/vendor-packages/_pytest/python.py:459: in collect
    res = self.makeitem(name, obj)
/usr/lib/python3.7/vendor-packages/_pytest/python.py:471: in makeitem
    collector=self, name=name, obj=obj)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:724: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:338: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:333: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:595: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.7/vendor-packages/_pytest/vendored_packages/pluggy.py:249: in _wrapped_call
    wrap_controller.send(call_outcome)
E   RuntimeError: generator raised StopIteration
 27 passed, 37 error in  x seconds
